(define (problem scrisp-give1)
   (:domain scrisp-give1)
    (:objects
        b1_dist1 - individual
        chair1 - individual
        b1_dist2 - individual
        p1 - individual
        b1_dist3 - individual
        pos_11_7 - positiontype
        pos_11_6 - positiontype
        pos_11_5 - positiontype
        foo - individual
        pos_11_4 - positiontype
        pos_11_8 - positiontype
        bt1 - individual
        b5_dist1 - individual
        pos_2_0 - positiontype
        pos_2_1 - positiontype
        pos_2_2 - positiontype
        pos_2_3 - positiontype
        pos_2_4 - positiontype
        pos_0_1 - positiontype
        pos_2_5 - positiontype
        pos_0_0 - positiontype
        pos_2_6 - positiontype
        b3_dist1 - individual
        pos_2_7 - positiontype
        pos_0_5 - positiontype
        bt2 - individual
        pos_0_4 - positiontype
        bt3 - individual
        pos_0_3 - positiontype
        b4_dist2 - individual
        pos_0_2 - positiontype
        b4_dist1 - individual
        pos_0_8 - positiontype
        pos_0_7 - positiontype
        pos_0_6 - positiontype
        pos_11_0 - positiontype
        pos_11_1 - positiontype
        pos_11_2 - positiontype
        pos_11_3 - positiontype
        pos_8_1 - positiontype
        pos_8_0 - positiontype
        pos_4_0 - positiontype
        a1 - individual
        pos_4_1 - positiontype
        pos_4_4 - positiontype
        pos_4_5 - positiontype
        pos_4_2 - positiontype
        pos_4_3 - positiontype
        pos_6_1 - positiontype
        pos_6_0 - positiontype
        pos_6_3 - positiontype
        pos_6_2 - positiontype
        south - orientationtype
        root - syntaxnode
        pos_10_5 - positiontype
        b6_dist1 - individual
        pos_10_6 - positiontype
        b6_dist2 - individual
        pos_10_7 - positiontype
        pos_10_8 - positiontype
        pos_10_4 - positiontype
        pos_3_7 - positiontype
        pos_3_8 - positiontype
        pos_10_3 - positiontype
        pos_10_2 - positiontype
        pos_10_1 - positiontype
        pos_10_0 - positiontype
        pos_9_7 - positiontype
        pos_9_8 - positiontype
        pos_9_5 - positiontype
        pos_9_6 - positiontype
        pos_9_3 - positiontype
        pos_4_6 - positiontype
        pos_9_4 - positiontype
        pos_4_7 - positiontype
        pos_4_8 - positiontype
        pos_9_1 - positiontype
        pos_9_2 - positiontype
        pos_1_8 - positiontype
        pos_6_8 - positiontype
        pos_1_7 - positiontype
        pos_7_8 - positiontype
        pos_1_6 - positiontype
        pos_7_7 - positiontype
        pos_1_5 - positiontype
        pos_7_6 - positiontype
        pos_6_5 - positiontype
        pos_1_4 - positiontype
        pos_7_5 - positiontype
        pos_6_4 - positiontype
        pos_1_3 - positiontype
        pos_6_7 - positiontype
        pos_1_2 - positiontype
        pos_7_4 - positiontype
        pos_1_1 - positiontype
        pos_7_3 - positiontype
        pos_6_6 - positiontype
        pos_8_5 - positiontype
        pos_5_6 - positiontype
        pos_1_0 - positiontype
        pos_8_4 - positiontype
        pos_5_5 - positiontype
        pos_5_8 - positiontype
        pos_8_3 - positiontype
        pos_8_2 - positiontype
        pos_5_7 - positiontype
        pos_8_8 - positiontype
        pos_8_7 - positiontype
        west - orientationtype
        pos_8_6 - positiontype
        pos_5_3 - positiontype
        b2_dist1 - individual
        pos_5_4 - positiontype
        b2_dist2 - individual
        pos_5_1 - positiontype
        t1 - individual
        pos_5_2 - positiontype
        pos_2_8 - positiontype
        pos_5_0 - positiontype
        b3 - individual
        b2 - individual
        b5 - individual
        north - orientationtype
        b4 - individual
        b6 - individual
        pos_7_0 - positiontype
        pos_7_1 - positiontype
        pos_7_2 - positiontype
        pos_9_0 - positiontype
        flower1 - individual
        b1 - individual
        e-4 - individual
        pos_3_6 - positiontype
        pos_3_5 - positiontype
        pos_3_4 - positiontype
        pos_3_3 - positiontype
        east - orientationtype
        pos_3_2 - positiontype
        e-1 - individual
        pos_3_1 - positiontype
        e-2 - individual
        pos_3_0 - positiontype
        e-3 - individual
        lamp1 - individual
        n-5 - syntaxnode
        n-4 - syntaxnode
        n-3 - syntaxnode
        s1 - individual
        n-2 - syntaxnode
        n-1 - syntaxnode
        dt1 - individual
        pt1 - individual
    )
   (:init
      (subst s root)
      (referent root e-1)
      (needtoexpress-1 imp-push b6)
      (conj-node foo)
      (target b6)
      (player-position pos_5_1)
      (player-orientation north)
      (blocked pos_1_7 pos_1_6)
      (blocked pos_5_7 pos_5_6)
      (blocked pos_4_7 pos_4_6)
      (blocked pos_1_1 pos_1_0)
      (blocked pos_1_0 pos_1_1)
      (blocked pos_7_3 pos_7_4)
      (blocked pos_1_6 pos_0_6)
      (blocked pos_6_4 pos_6_3)
      (blocked pos_3_7 pos_3_6)
      (blocked pos_6_1 pos_6_0)
      (blocked pos_6_1 pos_5_1)
      (blocked pos_9_1 pos_10_1)
      (blocked pos_1_2 pos_0_2)
      (blocked pos_5_1 pos_6_1)
      (blocked pos_6_4 pos_5_4)
      (blocked pos_2_0 pos_2_1)
      (blocked pos_10_2 pos_9_2)
      (alarmed pos_5_5)
      (blocked pos_8_4 pos_8_3)
      (blocked pos_5_6 pos_5_7)
      (blocked pos_9_3 pos_9_4)
      (blocked pos_0_4 pos_1_4)
      (blocked pos_6_5 pos_5_5)
      (blocked pos_5_2 pos_6_2)
      (blocked pos_9_2 pos_10_2)
      (blocked pos_0_1 pos_1_1)
      (blocked pos_4_1 pos_4_0)
      (blocked pos_1_1 pos_0_1)
      (blocked pos_9_4 pos_9_3)
      (blocked pos_0_6 pos_1_6)
      (blocked pos_1_5 pos_0_5)
      (blocked pos_4_0 pos_4_1)
      (blocked pos_8_3 pos_8_4)
      (blocked pos_5_1 pos_5_0)
      (blocked pos_3_6 pos_3_7)
      (blocked pos_9_3 pos_10_3)
      (blocked pos_1_3 pos_0_3)
      (blocked pos_1_6 pos_1_7)
      (blocked pos_7_4 pos_7_3)
      (blocked pos_2_7 pos_2_6)
      (blocked pos_0_5 pos_1_5)
      (blocked pos_5_4 pos_6_4)
      (blocked pos_6_3 pos_5_3)
      (blocked pos_2_6 pos_2_7)
      (blocked pos_6_0 pos_6_1)
      (blocked pos_6_3 pos_6_4)
      (blocked pos_6_6 pos_5_6)
      (blocked pos_0_2 pos_1_2)
      (blocked pos_0_3 pos_1_3)
      (blocked pos_5_5 pos_6_5)
      (blocked pos_5_0 pos_5_1)
      (blocked pos_10_1 pos_9_1)
      (blocked pos_7_0 pos_7_1)
      (blocked pos_10_3 pos_9_3)
      (blocked pos_9_1 pos_9_0)
      (blocked pos_5_6 pos_6_6)
      (blocked pos_8_1 pos_8_0)
      (blocked pos_6_2 pos_5_2)
      (blocked pos_7_1 pos_7_0)
      (blocked pos_8_0 pos_8_1)
      (blocked pos_5_3 pos_6_3)
      (blocked pos_3_1 pos_3_0)
      (blocked pos_9_0 pos_9_1)
      (blocked pos_1_4 pos_0_4)
      (blocked pos_3_0 pos_3_1)
      (blocked pos_4_6 pos_4_7)
      (blocked pos_2_1 pos_2_0)
      (button b1_dist1)
      (green b1_dist1)
      (object-position b1_dist1 pos_1_5)
      (object-orientation b1_dist1 east)
      (chair chair1)
      (button b1_dist2)
      (blue b1_dist2)
      (object-position b1_dist2 pos_1_5)
      (object-orientation b1_dist2 east)
      (picture p1)
      (button b1_dist3)
      (green b1_dist3)
      (object-position b1_dist3 pos_1_5)
      (object-orientation b1_dist3 east)
      (button bt1)
      (blue bt1)
      (object-position bt1 pos_6_1)
      (object-orientation bt1 north)
      (button b5_dist1)
      (blue b5_dist1)
      (object-position b5_dist1 pos_4_6)
      (object-orientation b5_dist1 south)
      (button b6_dist1)
      (blue b6_dist1)
      (object-position b6_dist1 pos_5_3)
      (object-orientation b6_dist1 west)
      (button b6_dist2)
      (red b6_dist2)
      (object-position b6_dist2 pos_5_3)
      (object-orientation b6_dist2 west)
      (button b3_dist1)
      (blue b3_dist1)
      (object-position b3_dist1 pos_4_1)
      (object-orientation b3_dist1 north)
      (button bt2)
      (green bt2)
      (object-position bt2 pos_9_3)
      (object-orientation bt2 south)
      (button bt3)
      (red bt3)
      (object-position bt3 pos_9_3)
      (object-orientation bt3 south)
      (button b4_dist2)
      (red b4_dist2)
      (object-position b4_dist2 pos_1_1)
      (object-orientation b4_dist2 east)
      (button b4_dist1)
      (red b4_dist1)
      (object-position b4_dist1 pos_1_3)
      (object-orientation b4_dist1 east)
      (button b2_dist1)
      (red b2_dist1)
      (object-position b2_dist1 pos_5_6)
      (object-orientation b2_dist1 west)
      (button b2_dist2)
      (blue b2_dist2)
      (object-position b2_dist2 pos_5_6)
      (object-orientation b2_dist2 south)
      (trophy t1)
      (button b3)
      (blue b3)
      (object-position b3 pos_4_1)
      (object-orientation b3 north)
      (button b2)
      (red b2)
      (object-position b2 pos_5_6)
      (object-orientation b2 south)
      (button b5)
      (red b5)
      (object-position b5 pos_4_6)
      (object-orientation b5 south)
      (button b4)
      (red b4)
      (object-position b4 pos_1_1)
      (object-orientation b4 east)
      (button b6)
      (green b6)
      (object-position b6 pos_5_3)
      (object-orientation b6 west)
      (flower flower1)
      (button b1)
      (blue b1)
      (object-position b1 pos_1_5)
      (object-orientation b1 east)
      (alarm a1)
      (lamp lamp1)
      (safe s1)
      (door dt1)
      (picture pt1)
      (next-orientation-left north west)
      (next-orientation-left west south)
      (next-orientation-left south east)
      (next-orientation-left east north)
      (adjacent pos_0_0 pos_0_1 north)
      (adjacent pos_0_0 pos_1_0 east)
      (adjacent pos_0_1 pos_0_0 south)
      (adjacent pos_0_1 pos_0_2 north)
      (adjacent pos_0_1 pos_1_1 east)
      (adjacent pos_0_2 pos_0_1 south)
      (adjacent pos_0_2 pos_0_3 north)
      (adjacent pos_0_2 pos_1_2 east)
      (adjacent pos_0_3 pos_0_2 south)
      (adjacent pos_0_3 pos_0_4 north)
      (adjacent pos_0_3 pos_1_3 east)
      (adjacent pos_0_4 pos_0_3 south)
      (adjacent pos_0_4 pos_0_5 north)
      (adjacent pos_0_4 pos_1_4 east)
      (adjacent pos_0_5 pos_0_4 south)
      (adjacent pos_0_5 pos_0_6 north)
      (adjacent pos_0_5 pos_1_5 east)
      (adjacent pos_0_6 pos_0_5 south)
      (adjacent pos_0_6 pos_0_7 north)
      (adjacent pos_0_6 pos_1_6 east)
      (adjacent pos_0_7 pos_0_6 south)
      (adjacent pos_0_7 pos_0_8 north)
      (adjacent pos_0_7 pos_1_7 east)
      (adjacent pos_0_8 pos_0_7 south)
      (adjacent pos_0_8 pos_1_8 east)
      (adjacent pos_1_0 pos_0_0 west)
      (adjacent pos_1_0 pos_1_1 north)
      (adjacent pos_1_0 pos_2_0 east)
      (adjacent pos_1_1 pos_0_1 west)
      (adjacent pos_1_1 pos_1_0 south)
      (adjacent pos_1_1 pos_1_2 north)
      (adjacent pos_1_1 pos_2_1 east)
      (adjacent pos_1_2 pos_0_2 west)
      (adjacent pos_1_2 pos_1_1 south)
      (adjacent pos_1_2 pos_1_3 north)
      (adjacent pos_1_2 pos_2_2 east)
      (adjacent pos_1_3 pos_0_3 west)
      (adjacent pos_1_3 pos_1_2 south)
      (adjacent pos_1_3 pos_1_4 north)
      (adjacent pos_1_3 pos_2_3 east)
      (adjacent pos_1_4 pos_0_4 west)
      (adjacent pos_1_4 pos_1_3 south)
      (adjacent pos_1_4 pos_1_5 north)
      (adjacent pos_1_4 pos_2_4 east)
      (adjacent pos_1_5 pos_0_5 west)
      (adjacent pos_1_5 pos_1_4 south)
      (adjacent pos_1_5 pos_1_6 north)
      (adjacent pos_1_5 pos_2_5 east)
      (adjacent pos_1_6 pos_0_6 west)
      (adjacent pos_1_6 pos_1_5 south)
      (adjacent pos_1_6 pos_1_7 north)
      (adjacent pos_1_6 pos_2_6 east)
      (adjacent pos_1_7 pos_0_7 west)
      (adjacent pos_1_7 pos_1_6 south)
      (adjacent pos_1_7 pos_1_8 north)
      (adjacent pos_1_7 pos_2_7 east)
      (adjacent pos_1_8 pos_0_8 west)
      (adjacent pos_1_8 pos_1_7 south)
      (adjacent pos_1_8 pos_2_8 east)
      (adjacent pos_2_0 pos_1_0 west)
      (adjacent pos_2_0 pos_2_1 north)
      (adjacent pos_2_0 pos_3_0 east)
      (adjacent pos_2_1 pos_1_1 west)
      (adjacent pos_2_1 pos_2_0 south)
      (adjacent pos_2_1 pos_2_2 north)
      (adjacent pos_2_1 pos_3_1 east)
      (adjacent pos_2_2 pos_1_2 west)
      (adjacent pos_2_2 pos_2_1 south)
      (adjacent pos_2_2 pos_2_3 north)
      (adjacent pos_2_2 pos_3_2 east)
      (adjacent pos_2_3 pos_1_3 west)
      (adjacent pos_2_3 pos_2_2 south)
      (adjacent pos_2_3 pos_2_4 north)
      (adjacent pos_2_3 pos_3_3 east)
      (adjacent pos_2_4 pos_1_4 west)
      (adjacent pos_2_4 pos_2_3 south)
      (adjacent pos_2_4 pos_2_5 north)
      (adjacent pos_2_4 pos_3_4 east)
      (adjacent pos_2_5 pos_1_5 west)
      (adjacent pos_2_5 pos_2_4 south)
      (adjacent pos_2_5 pos_2_6 north)
      (adjacent pos_2_5 pos_3_5 east)
      (adjacent pos_2_6 pos_1_6 west)
      (adjacent pos_2_6 pos_2_5 south)
      (adjacent pos_2_6 pos_2_7 north)
      (adjacent pos_2_6 pos_3_6 east)
      (adjacent pos_2_7 pos_1_7 west)
      (adjacent pos_2_7 pos_2_6 south)
      (adjacent pos_2_7 pos_2_8 north)
      (adjacent pos_2_7 pos_3_7 east)
      (adjacent pos_2_8 pos_1_8 west)
      (adjacent pos_2_8 pos_2_7 south)
      (adjacent pos_2_8 pos_3_8 east)
      (adjacent pos_3_0 pos_2_0 west)
      (adjacent pos_3_0 pos_3_1 north)
      (adjacent pos_3_0 pos_4_0 east)
      (adjacent pos_3_1 pos_2_1 west)
      (adjacent pos_3_1 pos_3_0 south)
      (adjacent pos_3_1 pos_3_2 north)
      (adjacent pos_3_1 pos_4_1 east)
      (adjacent pos_3_2 pos_2_2 west)
      (adjacent pos_3_2 pos_3_1 south)
      (adjacent pos_3_2 pos_3_3 north)
      (adjacent pos_3_2 pos_4_2 east)
      (adjacent pos_3_3 pos_2_3 west)
      (adjacent pos_3_3 pos_3_2 south)
      (adjacent pos_3_3 pos_3_4 north)
      (adjacent pos_3_3 pos_4_3 east)
      (adjacent pos_3_4 pos_2_4 west)
      (adjacent pos_3_4 pos_3_3 south)
      (adjacent pos_3_4 pos_3_5 north)
      (adjacent pos_3_4 pos_4_4 east)
      (adjacent pos_3_5 pos_2_5 west)
      (adjacent pos_3_5 pos_3_4 south)
      (adjacent pos_3_5 pos_3_6 north)
      (adjacent pos_3_5 pos_4_5 east)
      (adjacent pos_3_6 pos_2_6 west)
      (adjacent pos_3_6 pos_3_5 south)
      (adjacent pos_3_6 pos_3_7 north)
      (adjacent pos_3_6 pos_4_6 east)
      (adjacent pos_3_7 pos_2_7 west)
      (adjacent pos_3_7 pos_3_6 south)
      (adjacent pos_3_7 pos_3_8 north)
      (adjacent pos_3_7 pos_4_7 east)
      (adjacent pos_3_8 pos_2_8 west)
      (adjacent pos_3_8 pos_3_7 south)
      (adjacent pos_3_8 pos_4_8 east)
      (adjacent pos_4_0 pos_3_0 west)
      (adjacent pos_4_0 pos_4_1 north)
      (adjacent pos_4_0 pos_5_0 east)
      (adjacent pos_4_1 pos_3_1 west)
      (adjacent pos_4_1 pos_4_0 south)
      (adjacent pos_4_1 pos_4_2 north)
      (adjacent pos_4_1 pos_5_1 east)
      (adjacent pos_4_2 pos_3_2 west)
      (adjacent pos_4_2 pos_4_1 south)
      (adjacent pos_4_2 pos_4_3 north)
      (adjacent pos_4_2 pos_5_2 east)
      (adjacent pos_4_3 pos_3_3 west)
      (adjacent pos_4_3 pos_4_2 south)
      (adjacent pos_4_3 pos_4_4 north)
      (adjacent pos_4_3 pos_5_3 east)
      (adjacent pos_4_4 pos_3_4 west)
      (adjacent pos_4_4 pos_4_3 south)
      (adjacent pos_4_4 pos_4_5 north)
      (adjacent pos_4_4 pos_5_4 east)
      (adjacent pos_4_5 pos_3_5 west)
      (adjacent pos_4_5 pos_4_4 south)
      (adjacent pos_4_5 pos_4_6 north)
      (adjacent pos_4_5 pos_5_5 east)
      (adjacent pos_4_6 pos_3_6 west)
      (adjacent pos_4_6 pos_4_5 south)
      (adjacent pos_4_6 pos_4_7 north)
      (adjacent pos_4_6 pos_5_6 east)
      (adjacent pos_4_7 pos_3_7 west)
      (adjacent pos_4_7 pos_4_6 south)
      (adjacent pos_4_7 pos_4_8 north)
      (adjacent pos_4_7 pos_5_7 east)
      (adjacent pos_4_8 pos_3_8 west)
      (adjacent pos_4_8 pos_4_7 south)
      (adjacent pos_4_8 pos_5_8 east)
      (adjacent pos_5_0 pos_4_0 west)
      (adjacent pos_5_0 pos_5_1 north)
      (adjacent pos_5_0 pos_6_0 east)
      (adjacent pos_5_1 pos_4_1 west)
      (adjacent pos_5_1 pos_5_0 south)
      (adjacent pos_5_1 pos_5_2 north)
      (adjacent pos_5_1 pos_6_1 east)
      (adjacent pos_5_2 pos_4_2 west)
      (adjacent pos_5_2 pos_5_1 south)
      (adjacent pos_5_2 pos_5_3 north)
      (adjacent pos_5_2 pos_6_2 east)
      (adjacent pos_5_3 pos_4_3 west)
      (adjacent pos_5_3 pos_5_2 south)
      (adjacent pos_5_3 pos_5_4 north)
      (adjacent pos_5_3 pos_6_3 east)
      (adjacent pos_5_4 pos_4_4 west)
      (adjacent pos_5_4 pos_5_3 south)
      (adjacent pos_5_4 pos_5_5 north)
      (adjacent pos_5_4 pos_6_4 east)
      (adjacent pos_5_5 pos_4_5 west)
      (adjacent pos_5_5 pos_5_4 south)
      (adjacent pos_5_5 pos_5_6 north)
      (adjacent pos_5_5 pos_6_5 east)
      (adjacent pos_5_6 pos_4_6 west)
      (adjacent pos_5_6 pos_5_5 south)
      (adjacent pos_5_6 pos_5_7 north)
      (adjacent pos_5_6 pos_6_6 east)
      (adjacent pos_5_7 pos_4_7 west)
      (adjacent pos_5_7 pos_5_6 south)
      (adjacent pos_5_7 pos_5_8 north)
      (adjacent pos_5_7 pos_6_7 east)
      (adjacent pos_5_8 pos_4_8 west)
      (adjacent pos_5_8 pos_5_7 south)
      (adjacent pos_5_8 pos_6_8 east)
      (adjacent pos_6_0 pos_5_0 west)
      (adjacent pos_6_0 pos_6_1 north)
      (adjacent pos_6_0 pos_7_0 east)
      (adjacent pos_6_1 pos_5_1 west)
      (adjacent pos_6_1 pos_6_0 south)
      (adjacent pos_6_1 pos_6_2 north)
      (adjacent pos_6_1 pos_7_1 east)
      (adjacent pos_6_2 pos_5_2 west)
      (adjacent pos_6_2 pos_6_1 south)
      (adjacent pos_6_2 pos_6_3 north)
      (adjacent pos_6_2 pos_7_2 east)
      (adjacent pos_6_3 pos_5_3 west)
      (adjacent pos_6_3 pos_6_2 south)
      (adjacent pos_6_3 pos_6_4 north)
      (adjacent pos_6_3 pos_7_3 east)
      (adjacent pos_6_4 pos_5_4 west)
      (adjacent pos_6_4 pos_6_3 south)
      (adjacent pos_6_4 pos_6_5 north)
      (adjacent pos_6_4 pos_7_4 east)
      (adjacent pos_6_5 pos_5_5 west)
      (adjacent pos_6_5 pos_6_4 south)
      (adjacent pos_6_5 pos_6_6 north)
      (adjacent pos_6_5 pos_7_5 east)
      (adjacent pos_6_6 pos_5_6 west)
      (adjacent pos_6_6 pos_6_5 south)
      (adjacent pos_6_6 pos_6_7 north)
      (adjacent pos_6_6 pos_7_6 east)
      (adjacent pos_6_7 pos_5_7 west)
      (adjacent pos_6_7 pos_6_6 south)
      (adjacent pos_6_7 pos_6_8 north)
      (adjacent pos_6_7 pos_7_7 east)
      (adjacent pos_6_8 pos_5_8 west)
      (adjacent pos_6_8 pos_6_7 south)
      (adjacent pos_6_8 pos_7_8 east)
      (adjacent pos_7_0 pos_6_0 west)
      (adjacent pos_7_0 pos_7_1 north)
      (adjacent pos_7_0 pos_8_0 east)
      (adjacent pos_7_1 pos_6_1 west)
      (adjacent pos_7_1 pos_7_0 south)
      (adjacent pos_7_1 pos_7_2 north)
      (adjacent pos_7_1 pos_8_1 east)
      (adjacent pos_7_2 pos_6_2 west)
      (adjacent pos_7_2 pos_7_1 south)
      (adjacent pos_7_2 pos_7_3 north)
      (adjacent pos_7_2 pos_8_2 east)
      (adjacent pos_7_3 pos_6_3 west)
      (adjacent pos_7_3 pos_7_2 south)
      (adjacent pos_7_3 pos_7_4 north)
      (adjacent pos_7_3 pos_8_3 east)
      (adjacent pos_7_4 pos_6_4 west)
      (adjacent pos_7_4 pos_7_3 south)
      (adjacent pos_7_4 pos_7_5 north)
      (adjacent pos_7_4 pos_8_4 east)
      (adjacent pos_7_5 pos_6_5 west)
      (adjacent pos_7_5 pos_7_4 south)
      (adjacent pos_7_5 pos_7_6 north)
      (adjacent pos_7_5 pos_8_5 east)
      (adjacent pos_7_6 pos_6_6 west)
      (adjacent pos_7_6 pos_7_5 south)
      (adjacent pos_7_6 pos_7_7 north)
      (adjacent pos_7_6 pos_8_6 east)
      (adjacent pos_7_7 pos_6_7 west)
      (adjacent pos_7_7 pos_7_6 south)
      (adjacent pos_7_7 pos_7_8 north)
      (adjacent pos_7_7 pos_8_7 east)
      (adjacent pos_7_8 pos_6_8 west)
      (adjacent pos_7_8 pos_7_7 south)
      (adjacent pos_7_8 pos_8_8 east)
      (adjacent pos_8_0 pos_7_0 west)
      (adjacent pos_8_0 pos_8_1 north)
      (adjacent pos_8_0 pos_9_0 east)
      (adjacent pos_8_1 pos_7_1 west)
      (adjacent pos_8_1 pos_8_0 south)
      (adjacent pos_8_1 pos_8_2 north)
      (adjacent pos_8_1 pos_9_1 east)
      (adjacent pos_8_2 pos_7_2 west)
      (adjacent pos_8_2 pos_8_1 south)
      (adjacent pos_8_2 pos_8_3 north)
      (adjacent pos_8_2 pos_9_2 east)
      (adjacent pos_8_3 pos_7_3 west)
      (adjacent pos_8_3 pos_8_2 south)
      (adjacent pos_8_3 pos_8_4 north)
      (adjacent pos_8_3 pos_9_3 east)
      (adjacent pos_8_4 pos_7_4 west)
      (adjacent pos_8_4 pos_8_3 south)
      (adjacent pos_8_4 pos_8_5 north)
      (adjacent pos_8_4 pos_9_4 east)
      (adjacent pos_8_5 pos_7_5 west)
      (adjacent pos_8_5 pos_8_4 south)
      (adjacent pos_8_5 pos_8_6 north)
      (adjacent pos_8_5 pos_9_5 east)
      (adjacent pos_8_6 pos_7_6 west)
      (adjacent pos_8_6 pos_8_5 south)
      (adjacent pos_8_6 pos_8_7 north)
      (adjacent pos_8_6 pos_9_6 east)
      (adjacent pos_8_7 pos_7_7 west)
      (adjacent pos_8_7 pos_8_6 south)
      (adjacent pos_8_7 pos_8_8 north)
      (adjacent pos_8_7 pos_9_7 east)
      (adjacent pos_8_8 pos_7_8 west)
      (adjacent pos_8_8 pos_8_7 south)
      (adjacent pos_8_8 pos_9_8 east)
      (adjacent pos_9_0 pos_8_0 west)
      (adjacent pos_9_0 pos_9_1 north)
      (adjacent pos_9_0 pos_10_0 east)
      (adjacent pos_9_1 pos_8_1 west)
      (adjacent pos_9_1 pos_9_0 south)
      (adjacent pos_9_1 pos_9_2 north)
      (adjacent pos_9_1 pos_10_1 east)
      (adjacent pos_9_2 pos_8_2 west)
      (adjacent pos_9_2 pos_9_1 south)
      (adjacent pos_9_2 pos_9_3 north)
      (adjacent pos_9_2 pos_10_2 east)
      (adjacent pos_9_3 pos_8_3 west)
      (adjacent pos_9_3 pos_9_2 south)
      (adjacent pos_9_3 pos_9_4 north)
      (adjacent pos_9_3 pos_10_3 east)
      (adjacent pos_9_4 pos_8_4 west)
      (adjacent pos_9_4 pos_9_3 south)
      (adjacent pos_9_4 pos_9_5 north)
      (adjacent pos_9_4 pos_10_4 east)
      (adjacent pos_9_5 pos_8_5 west)
      (adjacent pos_9_5 pos_9_4 south)
      (adjacent pos_9_5 pos_9_6 north)
      (adjacent pos_9_5 pos_10_5 east)
      (adjacent pos_9_6 pos_8_6 west)
      (adjacent pos_9_6 pos_9_5 south)
      (adjacent pos_9_6 pos_9_7 north)
      (adjacent pos_9_6 pos_10_6 east)
      (adjacent pos_9_7 pos_8_7 west)
      (adjacent pos_9_7 pos_9_6 south)
      (adjacent pos_9_7 pos_9_8 north)
      (adjacent pos_9_7 pos_10_7 east)
      (adjacent pos_9_8 pos_8_8 west)
      (adjacent pos_9_8 pos_9_7 south)
      (adjacent pos_9_8 pos_10_8 east)
      (adjacent pos_10_0 pos_9_0 west)
      (adjacent pos_10_0 pos_10_1 north)
      (adjacent pos_10_0 pos_11_0 east)
      (adjacent pos_10_1 pos_9_1 west)
      (adjacent pos_10_1 pos_10_0 south)
      (adjacent pos_10_1 pos_10_2 north)
      (adjacent pos_10_1 pos_11_1 east)
      (adjacent pos_10_2 pos_9_2 west)
      (adjacent pos_10_2 pos_10_1 south)
      (adjacent pos_10_2 pos_10_3 north)
      (adjacent pos_10_2 pos_11_2 east)
      (adjacent pos_10_3 pos_9_3 west)
      (adjacent pos_10_3 pos_10_2 south)
      (adjacent pos_10_3 pos_10_4 north)
      (adjacent pos_10_3 pos_11_3 east)
      (adjacent pos_10_4 pos_9_4 west)
      (adjacent pos_10_4 pos_10_3 south)
      (adjacent pos_10_4 pos_10_5 north)
      (adjacent pos_10_4 pos_11_4 east)
      (adjacent pos_10_5 pos_9_5 west)
      (adjacent pos_10_5 pos_10_4 south)
      (adjacent pos_10_5 pos_10_6 north)
      (adjacent pos_10_5 pos_11_5 east)
      (adjacent pos_10_6 pos_9_6 west)
      (adjacent pos_10_6 pos_10_5 south)
      (adjacent pos_10_6 pos_10_7 north)
      (adjacent pos_10_6 pos_11_6 east)
      (adjacent pos_10_7 pos_9_7 west)
      (adjacent pos_10_7 pos_10_6 south)
      (adjacent pos_10_7 pos_10_8 north)
      (adjacent pos_10_7 pos_11_7 east)
      (adjacent pos_10_8 pos_9_8 west)
      (adjacent pos_10_8 pos_10_7 south)
      (adjacent pos_10_8 pos_11_8 east)
      (adjacent pos_11_0 pos_10_0 west)
      (adjacent pos_11_0 pos_11_1 north)
      (adjacent pos_11_1 pos_10_1 west)
      (adjacent pos_11_1 pos_11_0 south)
      (adjacent pos_11_1 pos_11_2 north)
      (adjacent pos_11_2 pos_10_2 west)
      (adjacent pos_11_2 pos_11_1 south)
      (adjacent pos_11_2 pos_11_3 north)
      (adjacent pos_11_3 pos_10_3 west)
      (adjacent pos_11_3 pos_11_2 south)
      (adjacent pos_11_3 pos_11_4 north)
      (adjacent pos_11_4 pos_10_4 west)
      (adjacent pos_11_4 pos_11_3 south)
      (adjacent pos_11_4 pos_11_5 north)
      (adjacent pos_11_5 pos_10_5 west)
      (adjacent pos_11_5 pos_11_4 south)
      (adjacent pos_11_5 pos_11_6 north)
      (adjacent pos_11_6 pos_10_6 west)
      (adjacent pos_11_6 pos_11_5 south)
      (adjacent pos_11_6 pos_11_7 north)
      (adjacent pos_11_7 pos_10_7 west)
      (adjacent pos_11_7 pos_11_6 south)
      (adjacent pos_11_7 pos_11_8 north)
      (adjacent pos_11_8 pos_10_8 west)
      (adjacent pos_11_8 pos_11_7 south)
      (visible pos_1_1 east b3)
      (visible pos_1_1 east b3_dist1)
      (visible pos_1_1 east b6)
      (visible pos_1_1 east b6_dist1)
      (visible pos_1_1 east b6_dist2)
      (visible pos_1_1 east bt1)
      (visible pos_1_1 east chair1)
      (visible pos_1_1 east flower1)
      (visible pos_1_1 east p1)
      (visible pos_1_1 north b4)
      (visible pos_1_1 north b4_dist2)
      (visible pos_1_1 north flower1)
      (visible pos_1_1 west b4)
      (visible pos_1_1 west b4_dist2)
      (visible pos_1_2 east flower1)
      (visible pos_1_2 north flower1)
      (visible pos_1_2 south flower1)
      (visible pos_1_2 west flower1)
      (visible pos_1_3 east a1)
      (visible pos_1_3 east b2)
      (visible pos_1_3 east b2_dist1)
      (visible pos_1_3 east b2_dist2)
      (visible pos_1_3 east b3)
      (visible pos_1_3 east b3_dist1)
      (visible pos_1_3 east b5)
      (visible pos_1_3 east b5_dist1)
      (visible pos_1_3 east b6)
      (visible pos_1_3 east b6_dist1)
      (visible pos_1_3 east b6_dist2)
      (visible pos_1_3 east bt1)
      (visible pos_1_3 east chair1)
      (visible pos_1_3 east flower1)
      (visible pos_1_3 east p1)
      (visible pos_1_3 east s1)
      (visible pos_1_3 north b1)
      (visible pos_1_3 north b1_dist1)
      (visible pos_1_3 north b1_dist2)
      (visible pos_1_3 north b1_dist3)
      (visible pos_1_3 north b2)
      (visible pos_1_3 north b2_dist2)
      (visible pos_1_3 north b5)
      (visible pos_1_3 north b5_dist1)
      (visible pos_1_3 north lamp1)
      (visible pos_1_3 south b3)
      (visible pos_1_3 south b4_dist1)
      (visible pos_1_3 south chair1)
      (visible pos_1_3 south flower1)
      (visible pos_1_3 west b4_dist1)
      (visible pos_1_4 east a1)
      (visible pos_1_4 east b2)
      (visible pos_1_4 east b2_dist1)
      (visible pos_1_4 east b2_dist2)
      (visible pos_1_4 east b3)
      (visible pos_1_4 east b3_dist1)
      (visible pos_1_4 east b5)
      (visible pos_1_4 east b5_dist1)
      (visible pos_1_4 east b6)
      (visible pos_1_4 east b6_dist1)
      (visible pos_1_4 east b6_dist2)
      (visible pos_1_4 east bt1)
      (visible pos_1_4 east chair1)
      (visible pos_1_4 east p1)
      (visible pos_1_4 east s1)
      (visible pos_1_4 north b1)
      (visible pos_1_4 north b1_dist1)
      (visible pos_1_4 north b1_dist2)
      (visible pos_1_4 north b1_dist3)
      (visible pos_1_4 north b5_dist1)
      (visible pos_1_4 north lamp1)
      (visible pos_1_4 south b3)
      (visible pos_1_4 south b3_dist1)
      (visible pos_1_4 south b4_dist1)
      (visible pos_1_4 south chair1)
      (visible pos_1_4 south flower1)
      (visible pos_1_5 east a1)
      (visible pos_1_5 east b2)
      (visible pos_1_5 east b2_dist1)
      (visible pos_1_5 east b2_dist2)
      (visible pos_1_5 east b3_dist1)
      (visible pos_1_5 east b5)
      (visible pos_1_5 east b5_dist1)
      (visible pos_1_5 east b6)
      (visible pos_1_5 east b6_dist1)
      (visible pos_1_5 east b6_dist2)
      (visible pos_1_5 east bt1)
      (visible pos_1_5 east chair1)
      (visible pos_1_5 east lamp1)
      (visible pos_1_5 east p1)
      (visible pos_1_5 east s1)
      (visible pos_1_5 north b1)
      (visible pos_1_5 north b1_dist1)
      (visible pos_1_5 north lamp1)
      (visible pos_1_5 south b3)
      (visible pos_1_5 south b3_dist1)
      (visible pos_1_5 south b4_dist1)
      (visible pos_1_5 south bt1)
      (visible pos_1_5 south chair1)
      (visible pos_1_5 south flower1)
      (visible pos_1_5 west b1)
      (visible pos_1_5 west b1_dist1)
      (visible pos_1_5 west b1_dist2)
      (visible pos_1_5 west b1_dist3)
      (visible pos_1_6 east lamp1)
      (visible pos_1_6 north lamp1)
      (visible pos_1_6 south lamp1)
      (visible pos_1_6 west lamp1)
      (visible pos_2_1 east b3)
      (visible pos_2_1 east b3_dist1)
      (visible pos_2_1 east b6)
      (visible pos_2_1 east b6_dist1)
      (visible pos_2_1 east b6_dist2)
      (visible pos_2_1 east bt1)
      (visible pos_2_1 east chair1)
      (visible pos_2_1 east p1)
      (visible pos_2_1 east s1)
      (visible pos_2_1 north a1)
      (visible pos_2_1 north b1)
      (visible pos_2_1 north b1_dist1)
      (visible pos_2_1 north b1_dist2)
      (visible pos_2_1 north b1_dist3)
      (visible pos_2_1 north b2)
      (visible pos_2_1 north b2_dist1)
      (visible pos_2_1 north b2_dist2)
      (visible pos_2_1 north b5)
      (visible pos_2_1 north b5_dist1)
      (visible pos_2_1 north flower1)
      (visible pos_2_1 north lamp1)
      (visible pos_2_1 north p1)
      (visible pos_2_1 north s1)
      (visible pos_2_1 north t1)
      (visible pos_2_1 west b4)
      (visible pos_2_1 west b4_dist2)
      (visible pos_2_1 west flower1)
      (visible pos_2_2 east a1)
      (visible pos_2_2 east b2)
      (visible pos_2_2 east b2_dist1)
      (visible pos_2_2 east b3)
      (visible pos_2_2 east b3_dist1)
      (visible pos_2_2 east b6)
      (visible pos_2_2 east b6_dist1)
      (visible pos_2_2 east b6_dist2)
      (visible pos_2_2 east bt1)
      (visible pos_2_2 east chair1)
      (visible pos_2_2 east p1)
      (visible pos_2_2 east s1)
      (visible pos_2_2 north a1)
      (visible pos_2_2 north b1)
      (visible pos_2_2 north b1_dist1)
      (visible pos_2_2 north b1_dist2)
      (visible pos_2_2 north b1_dist3)
      (visible pos_2_2 north b2)
      (visible pos_2_2 north b2_dist1)
      (visible pos_2_2 north b2_dist2)
      (visible pos_2_2 north b5)
      (visible pos_2_2 north b5_dist1)
      (visible pos_2_2 north flower1)
      (visible pos_2_2 north lamp1)
      (visible pos_2_2 north p1)
      (visible pos_2_2 north s1)
      (visible pos_2_2 south b3)
      (visible pos_2_2 south chair1)
      (visible pos_2_2 south flower1)
      (visible pos_2_2 west flower1)
      (visible pos_2_3 east a1)
      (visible pos_2_3 east b2)
      (visible pos_2_3 east b2_dist1)
      (visible pos_2_3 east b2_dist2)
      (visible pos_2_3 east b3)
      (visible pos_2_3 east b3_dist1)
      (visible pos_2_3 east b6)
      (visible pos_2_3 east b6_dist1)
      (visible pos_2_3 east b6_dist2)
      (visible pos_2_3 east bt1)
      (visible pos_2_3 east chair1)
      (visible pos_2_3 east p1)
      (visible pos_2_3 east s1)
      (visible pos_2_3 north a1)
      (visible pos_2_3 north b1)
      (visible pos_2_3 north b1_dist1)
      (visible pos_2_3 north b1_dist2)
      (visible pos_2_3 north b1_dist3)
      (visible pos_2_3 north b2)
      (visible pos_2_3 north b2_dist1)
      (visible pos_2_3 north b2_dist2)
      (visible pos_2_3 north b5)
      (visible pos_2_3 north b5_dist1)
      (visible pos_2_3 north lamp1)
      (visible pos_2_3 south b3)
      (visible pos_2_3 south b3_dist1)
      (visible pos_2_3 south chair1)
      (visible pos_2_3 south flower1)
      (visible pos_2_3 west b4_dist1)
      (visible pos_2_3 west flower1)
      (visible pos_2_4 east a1)
      (visible pos_2_4 east b2)
      (visible pos_2_4 east b2_dist1)
      (visible pos_2_4 east b2_dist2)
      (visible pos_2_4 east b5)
      (visible pos_2_4 east b5_dist1)
      (visible pos_2_4 east b6)
      (visible pos_2_4 east b6_dist1)
      (visible pos_2_4 east b6_dist2)
      (visible pos_2_4 east bt1)
      (visible pos_2_4 east p1)
      (visible pos_2_4 east s1)
      (visible pos_2_4 north b1)
      (visible pos_2_4 north b1_dist1)
      (visible pos_2_4 north b2_dist2)
      (visible pos_2_4 north b5)
      (visible pos_2_4 north b5_dist1)
      (visible pos_2_4 north lamp1)
      (visible pos_2_4 south b3)
      (visible pos_2_4 south b3_dist1)
      (visible pos_2_4 south b4_dist1)
      (visible pos_2_4 south bt1)
      (visible pos_2_4 south chair1)
      (visible pos_2_4 south flower1)
      (visible pos_2_4 west b1)
      (visible pos_2_4 west b1_dist1)
      (visible pos_2_4 west b1_dist2)
      (visible pos_2_4 west b1_dist3)
      (visible pos_2_4 west b4_dist1)
      (visible pos_2_4 west lamp1)
      (visible pos_2_5 east a1)
      (visible pos_2_5 east b2)
      (visible pos_2_5 east b2_dist1)
      (visible pos_2_5 east b2_dist2)
      (visible pos_2_5 east b5)
      (visible pos_2_5 east b5_dist1)
      (visible pos_2_5 east b6)
      (visible pos_2_5 east b6_dist1)
      (visible pos_2_5 east b6_dist2)
      (visible pos_2_5 east bt1)
      (visible pos_2_5 east p1)
      (visible pos_2_5 east s1)
      (visible pos_2_5 north b5_dist1)
      (visible pos_2_5 north lamp1)
      (visible pos_2_5 south b3)
      (visible pos_2_5 south b3_dist1)
      (visible pos_2_5 south b4_dist1)
      (visible pos_2_5 south bt1)
      (visible pos_2_5 south chair1)
      (visible pos_2_5 south flower1)
      (visible pos_2_5 west b1)
      (visible pos_2_5 west b1_dist1)
      (visible pos_2_5 west b1_dist2)
      (visible pos_2_5 west b1_dist3)
      (visible pos_2_5 west lamp1)
      (visible pos_2_6 east a1)
      (visible pos_2_6 east b2)
      (visible pos_2_6 east b2_dist1)
      (visible pos_2_6 east b2_dist2)
      (visible pos_2_6 east b5)
      (visible pos_2_6 east b5_dist1)
      (visible pos_2_6 east b6)
      (visible pos_2_6 east b6_dist1)
      (visible pos_2_6 east b6_dist2)
      (visible pos_2_6 east bt1)
      (visible pos_2_6 east p1)
      (visible pos_2_6 east s1)
      (visible pos_2_6 south b3)
      (visible pos_2_6 south b3_dist1)
      (visible pos_2_6 south b4_dist1)
      (visible pos_2_6 south b6)
      (visible pos_2_6 south b6_dist1)
      (visible pos_2_6 south b6_dist2)
      (visible pos_2_6 south bt1)
      (visible pos_2_6 south chair1)
      (visible pos_2_6 south flower1)
      (visible pos_2_6 south lamp1)
      (visible pos_2_6 west lamp1)
      (visible pos_3_1 east b3)
      (visible pos_3_1 east b3_dist1)
      (visible pos_3_1 east b6)
      (visible pos_3_1 east b6_dist1)
      (visible pos_3_1 east b6_dist2)
      (visible pos_3_1 east bt1)
      (visible pos_3_1 east chair1)
      (visible pos_3_1 east p1)
      (visible pos_3_1 north a1)
      (visible pos_3_1 north b1)
      (visible pos_3_1 north b1_dist1)
      (visible pos_3_1 north b1_dist2)
      (visible pos_3_1 north b1_dist3)
      (visible pos_3_1 north b2)
      (visible pos_3_1 north b2_dist1)
      (visible pos_3_1 north b2_dist2)
      (visible pos_3_1 north b5)
      (visible pos_3_1 north b5_dist1)
      (visible pos_3_1 north b6_dist1)
      (visible pos_3_1 north b6_dist2)
      (visible pos_3_1 north flower1)
      (visible pos_3_1 north lamp1)
      (visible pos_3_1 north p1)
      (visible pos_3_1 north s1)
      (visible pos_3_1 south chair1)
      (visible pos_3_1 west b4)
      (visible pos_3_1 west b4_dist2)
      (visible pos_3_1 west flower1)
      (visible pos_3_2 east b3_dist1)
      (visible pos_3_2 east b6)
      (visible pos_3_2 east b6_dist1)
      (visible pos_3_2 east b6_dist2)
      (visible pos_3_2 east bt1)
      (visible pos_3_2 east chair1)
      (visible pos_3_2 east p1)
      (visible pos_3_2 north a1)
      (visible pos_3_2 north b1)
      (visible pos_3_2 north b1_dist1)
      (visible pos_3_2 north b1_dist2)
      (visible pos_3_2 north b1_dist3)
      (visible pos_3_2 north b2)
      (visible pos_3_2 north b2_dist1)
      (visible pos_3_2 north b2_dist2)
      (visible pos_3_2 north b5)
      (visible pos_3_2 north b5_dist1)
      (visible pos_3_2 north lamp1)
      (visible pos_3_2 north p1)
      (visible pos_3_2 north s1)
      (visible pos_3_2 south b3)
      (visible pos_3_2 south b3_dist1)
      (visible pos_3_2 south chair1)
      (visible pos_3_2 west b1_dist2)
      (visible pos_3_2 west b1_dist3)
      (visible pos_3_2 west b4_dist1)
      (visible pos_3_2 west flower1)
      (visible pos_3_3 east a1)
      (visible pos_3_3 east b2_dist1)
      (visible pos_3_3 east b6)
      (visible pos_3_3 east b6_dist1)
      (visible pos_3_3 east b6_dist2)
      (visible pos_3_3 east bt1)
      (visible pos_3_3 east p1)
      (visible pos_3_3 east s1)
      (visible pos_3_3 north a1)
      (visible pos_3_3 north b1)
      (visible pos_3_3 north b1_dist1)
      (visible pos_3_3 north b1_dist2)
      (visible pos_3_3 north b1_dist3)
      (visible pos_3_3 north b2)
      (visible pos_3_3 north b2_dist1)
      (visible pos_3_3 north b2_dist2)
      (visible pos_3_3 north b5)
      (visible pos_3_3 north b5_dist1)
      (visible pos_3_3 north lamp1)
      (visible pos_3_3 north p1)
      (visible pos_3_3 north s1)
      (visible pos_3_3 south b3)
      (visible pos_3_3 south b3_dist1)
      (visible pos_3_3 south bt1)
      (visible pos_3_3 south chair1)
      (visible pos_3_3 south flower1)
      (visible pos_3_3 west b1)
      (visible pos_3_3 west b1_dist1)
      (visible pos_3_3 west b1_dist2)
      (visible pos_3_3 west b1_dist3)
      (visible pos_3_3 west b4_dist1)
      (visible pos_3_3 west flower1)
      (visible pos_3_3 west lamp1)
      (visible pos_3_4 east a1)
      (visible pos_3_4 east b2)
      (visible pos_3_4 east b2_dist1)
      (visible pos_3_4 east b2_dist2)
      (visible pos_3_4 east b6)
      (visible pos_3_4 east b6_dist1)
      (visible pos_3_4 east b6_dist2)
      (visible pos_3_4 east bt1)
      (visible pos_3_4 east p1)
      (visible pos_3_4 east s1)
      (visible pos_3_4 north a1)
      (visible pos_3_4 north b2)
      (visible pos_3_4 north b2_dist1)
      (visible pos_3_4 north b2_dist2)
      (visible pos_3_4 north b5)
      (visible pos_3_4 north b5_dist1)
      (visible pos_3_4 north lamp1)
      (visible pos_3_4 south b3)
      (visible pos_3_4 south b3_dist1)
      (visible pos_3_4 south bt1)
      (visible pos_3_4 south chair1)
      (visible pos_3_4 south flower1)
      (visible pos_3_4 west b1)
      (visible pos_3_4 west b1_dist1)
      (visible pos_3_4 west b1_dist2)
      (visible pos_3_4 west b1_dist3)
      (visible pos_3_4 west b4_dist1)
      (visible pos_3_4 west flower1)
      (visible pos_3_4 west lamp1)
      (visible pos_3_5 east a1)
      (visible pos_3_5 east b2)
      (visible pos_3_5 east b2_dist1)
      (visible pos_3_5 east b2_dist2)
      (visible pos_3_5 east b5)
      (visible pos_3_5 east b6)
      (visible pos_3_5 east b6_dist1)
      (visible pos_3_5 east b6_dist2)
      (visible pos_3_5 east p1)
      (visible pos_3_5 east s1)
      (visible pos_3_5 north b2_dist2)
      (visible pos_3_5 north b5)
      (visible pos_3_5 north b5_dist1)
      (visible pos_3_5 north lamp1)
      (visible pos_3_5 south b3)
      (visible pos_3_5 south b3_dist1)
      (visible pos_3_5 south b4_dist1)
      (visible pos_3_5 south b6)
      (visible pos_3_5 south b6_dist1)
      (visible pos_3_5 south bt1)
      (visible pos_3_5 south chair1)
      (visible pos_3_5 south flower1)
      (visible pos_3_5 west b1)
      (visible pos_3_5 west b1_dist1)
      (visible pos_3_5 west b1_dist2)
      (visible pos_3_5 west b1_dist3)
      (visible pos_3_5 west b4_dist1)
      (visible pos_3_5 west flower1)
      (visible pos_3_5 west lamp1)
      (visible pos_3_6 east a1)
      (visible pos_3_6 east b2)
      (visible pos_3_6 east b2_dist1)
      (visible pos_3_6 east b2_dist2)
      (visible pos_3_6 east b5)
      (visible pos_3_6 east b5_dist1)
      (visible pos_3_6 east b6_dist1)
      (visible pos_3_6 east b6_dist2)
      (visible pos_3_6 east p1)
      (visible pos_3_6 east s1)
      (visible pos_3_6 south a1)
      (visible pos_3_6 south b3)
      (visible pos_3_6 south b3_dist1)
      (visible pos_3_6 south b4_dist1)
      (visible pos_3_6 south b6)
      (visible pos_3_6 south b6_dist1)
      (visible pos_3_6 south b6_dist2)
      (visible pos_3_6 south chair1)
      (visible pos_3_6 south flower1)
      (visible pos_3_6 south p1)
      (visible pos_3_6 west b1)
      (visible pos_3_6 west b1_dist1)
      (visible pos_3_6 west b1_dist2)
      (visible pos_3_6 west b1_dist3)
      (visible pos_3_6 west lamp1)
      (visible pos_4_1 east b3_dist1)
      (visible pos_4_1 east b6)
      (visible pos_4_1 east bt1)
      (visible pos_4_1 north a1)
      (visible pos_4_1 north b1)
      (visible pos_4_1 north b1_dist1)
      (visible pos_4_1 north b1_dist2)
      (visible pos_4_1 north b1_dist3)
      (visible pos_4_1 north b2)
      (visible pos_4_1 north b2_dist1)
      (visible pos_4_1 north b2_dist2)
      (visible pos_4_1 north b5)
      (visible pos_4_1 north b5_dist1)
      (visible pos_4_1 north b6)
      (visible pos_4_1 north b6_dist1)
      (visible pos_4_1 north b6_dist2)
      (visible pos_4_1 north chair1)
      (visible pos_4_1 north lamp1)
      (visible pos_4_1 north p1)
      (visible pos_4_1 north s1)
      (visible pos_4_1 south b3)
      (visible pos_4_1 south b3_dist1)
      (visible pos_4_1 south chair1)
      (visible pos_4_1 west b1)
      (visible pos_4_1 west b1_dist1)
      (visible pos_4_1 west b1_dist2)
      (visible pos_4_1 west b1_dist3)
      (visible pos_4_1 west b3)
      (visible pos_4_1 west b4)
      (visible pos_4_1 west b4_dist2)
      (visible pos_4_1 west chair1)
      (visible pos_4_1 west flower1)
      (visible pos_4_2 east b6)
      (visible pos_4_2 east b6_dist1)
      (visible pos_4_2 east b6_dist2)
      (visible pos_4_2 east bt1)
      (visible pos_4_2 north a1)
      (visible pos_4_2 north b1)
      (visible pos_4_2 north b1_dist1)
      (visible pos_4_2 north b1_dist2)
      (visible pos_4_2 north b1_dist3)
      (visible pos_4_2 north b2)
      (visible pos_4_2 north b2_dist1)
      (visible pos_4_2 north b2_dist2)
      (visible pos_4_2 north b5)
      (visible pos_4_2 north b5_dist1)
      (visible pos_4_2 north b6_dist1)
      (visible pos_4_2 north b6_dist2)
      (visible pos_4_2 north lamp1)
      (visible pos_4_2 north p1)
      (visible pos_4_2 north s1)
      (visible pos_4_2 south b3)
      (visible pos_4_2 south b3_dist1)
      (visible pos_4_2 south chair1)
      (visible pos_4_2 west b1)
      (visible pos_4_2 west b1_dist1)
      (visible pos_4_2 west b1_dist2)
      (visible pos_4_2 west b1_dist3)
      (visible pos_4_2 west b4_dist1)
      (visible pos_4_2 west flower1)
      (visible pos_4_2 west lamp1)
      (visible pos_4_3 east b6)
      (visible pos_4_3 east b6_dist1)
      (visible pos_4_3 east b6_dist2)
      (visible pos_4_3 east bt1)
      (visible pos_4_3 east p1)
      (visible pos_4_3 north a1)
      (visible pos_4_3 north b2)
      (visible pos_4_3 north b2_dist1)
      (visible pos_4_3 north b2_dist2)
      (visible pos_4_3 north b5)
      (visible pos_4_3 north b5_dist1)
      (visible pos_4_3 north lamp1)
      (visible pos_4_3 north p1)
      (visible pos_4_3 north s1)
      (visible pos_4_3 south b3)
      (visible pos_4_3 south b3_dist1)
      (visible pos_4_3 south bt1)
      (visible pos_4_3 south chair1)
      (visible pos_4_3 west b1)
      (visible pos_4_3 west b1_dist1)
      (visible pos_4_3 west b1_dist2)
      (visible pos_4_3 west b1_dist3)
      (visible pos_4_3 west b4_dist1)
      (visible pos_4_3 west flower1)
      (visible pos_4_3 west lamp1)
      (visible pos_4_4 east a1)
      (visible pos_4_4 east b6)
      (visible pos_4_4 east b6_dist1)
      (visible pos_4_4 east b6_dist2)
      (visible pos_4_4 east p1)
      (visible pos_4_4 east s1)
      (visible pos_4_4 north a1)
      (visible pos_4_4 north b2)
      (visible pos_4_4 north b2_dist1)
      (visible pos_4_4 north b2_dist2)
      (visible pos_4_4 north b5)
      (visible pos_4_4 north b5_dist1)
      (visible pos_4_4 north lamp1)
      (visible pos_4_4 north p1)
      (visible pos_4_4 north s1)
      (visible pos_4_4 south b3)
      (visible pos_4_4 south b3_dist1)
      (visible pos_4_4 south b6)
      (visible pos_4_4 south chair1)
      (visible pos_4_4 south flower1)
      (visible pos_4_4 west b1)
      (visible pos_4_4 west b1_dist1)
      (visible pos_4_4 west b1_dist2)
      (visible pos_4_4 west b1_dist3)
      (visible pos_4_4 west b4_dist1)
      (visible pos_4_4 west flower1)
      (visible pos_4_4 west lamp1)
      (visible pos_4_5 east a1)
      (visible pos_4_5 east b2)
      (visible pos_4_5 east b2_dist1)
      (visible pos_4_5 east b6_dist2)
      (visible pos_4_5 east p1)
      (visible pos_4_5 east s1)
      (visible pos_4_5 north a1)
      (visible pos_4_5 north b2)
      (visible pos_4_5 north b2_dist1)
      (visible pos_4_5 north b2_dist2)
      (visible pos_4_5 north b5)
      (visible pos_4_5 north b5_dist1)
      (visible pos_4_5 south a1)
      (visible pos_4_5 south b3)
      (visible pos_4_5 south b3_dist1)
      (visible pos_4_5 south b6)
      (visible pos_4_5 south b6_dist1)
      (visible pos_4_5 south b6_dist2)
      (visible pos_4_5 south chair1)
      (visible pos_4_5 south flower1)
      (visible pos_4_5 south p1)
      (visible pos_4_5 west b1)
      (visible pos_4_5 west b1_dist1)
      (visible pos_4_5 west b1_dist2)
      (visible pos_4_5 west b1_dist3)
      (visible pos_4_5 west b4_dist1)
      (visible pos_4_5 west flower1)
      (visible pos_4_5 west lamp1)
      (visible pos_4_6 east a1)
      (visible pos_4_6 east b2)
      (visible pos_4_6 east b2_dist1)
      (visible pos_4_6 east b2_dist2)
      (visible pos_4_6 east b5)
      (visible pos_4_6 east p1)
      (visible pos_4_6 east s1)
      (visible pos_4_6 north b5)
      (visible pos_4_6 north b5_dist1)
      (visible pos_4_6 south a1)
      (visible pos_4_6 south b3)
      (visible pos_4_6 south b3_dist1)
      (visible pos_4_6 south b4_dist1)
      (visible pos_4_6 south b6)
      (visible pos_4_6 south b6_dist1)
      (visible pos_4_6 south b6_dist2)
      (visible pos_4_6 south chair1)
      (visible pos_4_6 south flower1)
      (visible pos_4_6 south p1)
      (visible pos_4_6 south s1)
      (visible pos_4_6 west b1)
      (visible pos_4_6 west b1_dist1)
      (visible pos_4_6 west b1_dist2)
      (visible pos_4_6 west b1_dist3)
      (visible pos_4_6 west b4_dist1)
      (visible pos_4_6 west flower1)
      (visible pos_4_6 west lamp1)
      (visible pos_5_1 east bt1)
      (visible pos_5_1 east bt2)
      (visible pos_5_1 east bt3)
      (visible pos_5_1 north a1)
      (visible pos_5_1 north b1)
      (visible pos_5_1 north b1_dist1)
      (visible pos_5_1 north b1_dist2)
      (visible pos_5_1 north b1_dist3)
      (visible pos_5_1 north b2)
      (visible pos_5_1 north b2_dist1)
      (visible pos_5_1 north b2_dist2)
      (visible pos_5_1 north b5)
      (visible pos_5_1 north b5_dist1)
      (visible pos_5_1 north b6)
      (visible pos_5_1 north b6_dist1)
      (visible pos_5_1 north b6_dist2)
      (visible pos_5_1 north lamp1)
      (visible pos_5_1 north p1)
      (visible pos_5_1 north s1)
      (visible pos_5_1 west b1)
      (visible pos_5_1 west b1_dist1)
      (visible pos_5_1 west b1_dist2)
      (visible pos_5_1 west b1_dist3)
      (visible pos_5_1 west b3)
      (visible pos_5_1 west b3_dist1)
      (visible pos_5_1 west b4)
      (visible pos_5_1 west b4_dist1)
      (visible pos_5_1 west b4_dist2)
      (visible pos_5_1 west chair1)
      (visible pos_5_1 west flower1)
      (visible pos_5_1 west lamp1)
      (visible pos_5_2 east bt1)
      (visible pos_5_2 north a1)
      (visible pos_5_2 north b1)
      (visible pos_5_2 north b1_dist1)
      (visible pos_5_2 north b2)
      (visible pos_5_2 north b2_dist1)
      (visible pos_5_2 north b2_dist2)
      (visible pos_5_2 north b5)
      (visible pos_5_2 north b5_dist1)
      (visible pos_5_2 north b6)
      (visible pos_5_2 north b6_dist1)
      (visible pos_5_2 north b6_dist2)
      (visible pos_5_2 north lamp1)
      (visible pos_5_2 north p1)
      (visible pos_5_2 north s1)
      (visible pos_5_2 south b3)
      (visible pos_5_2 south b3_dist1)
      (visible pos_5_2 south bt1)
      (visible pos_5_2 south chair1)
      (visible pos_5_2 west b1)
      (visible pos_5_2 west b1_dist1)
      (visible pos_5_2 west b1_dist2)
      (visible pos_5_2 west b1_dist3)
      (visible pos_5_2 west b3)
      (visible pos_5_2 west b4_dist1)
      (visible pos_5_2 west chair1)
      (visible pos_5_2 west flower1)
      (visible pos_5_2 west lamp1)
      (visible pos_5_3 east b6)
      (visible pos_5_3 east b6_dist1)
      (visible pos_5_3 east b6_dist2)
      (visible pos_5_3 north a1)
      (visible pos_5_3 north b2)
      (visible pos_5_3 north b2_dist1)
      (visible pos_5_3 north b2_dist2)
      (visible pos_5_3 north b5)
      (visible pos_5_3 north b5_dist1)
      (visible pos_5_3 north b6_dist2)
      (visible pos_5_3 north lamp1)
      (visible pos_5_3 north p1)
      (visible pos_5_3 north s1)
      (visible pos_5_3 south b3)
      (visible pos_5_3 south b3_dist1)
      (visible pos_5_3 south b6)
      (visible pos_5_3 south chair1)
      (visible pos_5_3 west b1)
      (visible pos_5_3 west b1_dist1)
      (visible pos_5_3 west b1_dist2)
      (visible pos_5_3 west b1_dist3)
      (visible pos_5_3 west b4_dist1)
      (visible pos_5_3 west chair1)
      (visible pos_5_3 west flower1)
      (visible pos_5_3 west lamp1)
      (visible pos_5_4 east p1)
      (visible pos_5_4 north a1)
      (visible pos_5_4 north b2)
      (visible pos_5_4 north b2_dist1)
      (visible pos_5_4 north b2_dist2)
      (visible pos_5_4 north b5)
      (visible pos_5_4 north b5_dist1)
      (visible pos_5_4 north p1)
      (visible pos_5_4 north s1)
      (visible pos_5_4 south b3)
      (visible pos_5_4 south b3_dist1)
      (visible pos_5_4 south b6)
      (visible pos_5_4 south b6_dist1)
      (visible pos_5_4 south b6_dist2)
      (visible pos_5_4 south chair1)
      (visible pos_5_4 south flower1)
      (visible pos_5_4 south p1)
      (visible pos_5_4 west a1)
      (visible pos_5_4 west b1)
      (visible pos_5_4 west b1_dist1)
      (visible pos_5_4 west b1_dist2)
      (visible pos_5_4 west b1_dist3)
      (visible pos_5_4 west b4_dist1)
      (visible pos_5_4 west flower1)
      (visible pos_5_4 west lamp1)
      (visible pos_5_5 east p1)
      (visible pos_5_5 east s1)
      (visible pos_5_5 east t1)
      (visible pos_5_5 north a1)
      (visible pos_5_5 north b2)
      (visible pos_5_5 north b2_dist1)
      (visible pos_5_5 north b2_dist2)
      (visible pos_5_5 north b5)
      (visible pos_5_5 north b5_dist1)
      (visible pos_5_5 north p1)
      (visible pos_5_5 north s1)
      (visible pos_5_5 south a1)
      (visible pos_5_5 south b3)
      (visible pos_5_5 south b3_dist1)
      (visible pos_5_5 south b6)
      (visible pos_5_5 south b6_dist1)
      (visible pos_5_5 south b6_dist2)
      (visible pos_5_5 south chair1)
      (visible pos_5_5 south flower1)
      (visible pos_5_5 south p1)
      (visible pos_5_5 south s1)
      (visible pos_5_5 west a1)
      (visible pos_5_5 west b1)
      (visible pos_5_5 west b1_dist1)
      (visible pos_5_5 west b1_dist2)
      (visible pos_5_5 west b1_dist3)
      (visible pos_5_5 west b4_dist1)
      (visible pos_5_5 west b5_dist1)
      (visible pos_5_5 west flower1)
      (visible pos_5_5 west lamp1)
      (visible pos_5_6 east b2)
      (visible pos_5_6 east b2_dist1)
      (visible pos_5_6 north b2)
      (visible pos_5_6 north b2_dist2)
      (visible pos_5_6 south a1)
      (visible pos_5_6 south b3)
      (visible pos_5_6 south b3_dist1)
      (visible pos_5_6 south b4_dist1)
      (visible pos_5_6 south b6)
      (visible pos_5_6 south b6_dist1)
      (visible pos_5_6 south b6_dist2)
      (visible pos_5_6 south chair1)
      (visible pos_5_6 south flower1)
      (visible pos_5_6 south p1)
      (visible pos_5_6 south s1)
      (visible pos_5_6 west a1)
      (visible pos_5_6 west b1)
      (visible pos_5_6 west b1_dist1)
      (visible pos_5_6 west b1_dist2)
      (visible pos_5_6 west b1_dist3)
      (visible pos_5_6 west b2_dist2)
      (visible pos_5_6 west b4_dist1)
      (visible pos_5_6 west b5)
      (visible pos_5_6 west b5_dist1)
      (visible pos_5_6 west flower1)
      (visible pos_5_6 west lamp1)
      (visible pos_6_1 east bt2)
      (visible pos_6_1 east bt3)
      (visible pos_6_1 north b1)
      (visible pos_6_1 north b1_dist1)
      (visible pos_6_1 north bt2)
      (visible pos_6_1 north bt3)
      (visible pos_6_1 north lamp1)
      (visible pos_6_1 north pt1)
      (visible pos_6_1 south bt1)
      (visible pos_6_1 west b1)
      (visible pos_6_1 west b1_dist1)
      (visible pos_6_1 west b1_dist2)
      (visible pos_6_1 west b1_dist3)
      (visible pos_6_1 west b3)
      (visible pos_6_1 west b3_dist1)
      (visible pos_6_1 west b4)
      (visible pos_6_1 west b4_dist1)
      (visible pos_6_1 west b4_dist2)
      (visible pos_6_1 west chair1)
      (visible pos_6_1 west flower1)
      (visible pos_6_1 west lamp1)
      (visible pos_6_2 east bt2)
      (visible pos_6_2 east bt3)
      (visible pos_6_2 east pt1)
      (visible pos_6_2 north pt1)
      (visible pos_6_2 south bt1)
      (visible pos_6_2 south dt1)
      (visible pos_6_2 west dt1)
      (visible pos_6_3 east bt2)
      (visible pos_6_3 east bt3)
      (visible pos_6_3 east pt1)
      (visible pos_6_3 south bt1)
      (visible pos_6_3 south dt1)
      (visible pos_6_5 east s1)
      (visible pos_6_5 north b5)
      (visible pos_6_5 north s1)
      (visible pos_6_5 north t1)
      (visible pos_6_5 south flower1)
      (visible pos_6_5 south p1)
      (visible pos_6_5 south s1)
      (visible pos_6_5 south t1)
      (visible pos_6_5 west b5)
      (visible pos_6_5 west flower1)
      (visible pos_6_5 west p1)
      (visible pos_6_5 west s1)
      (visible pos_6_5 west t1)
      (visible pos_7_1 east bt2)
      (visible pos_7_1 east bt3)
      (visible pos_7_1 north bt2)
      (visible pos_7_1 north bt3)
      (visible pos_7_1 north pt1)
      (visible pos_7_1 west bt1)
      (visible pos_7_1 west dt1)
      (visible pos_7_2 east bt2)
      (visible pos_7_2 east bt3)
      (visible pos_7_2 east pt1)
      (visible pos_7_2 north pt1)
      (visible pos_7_2 south bt1)
      (visible pos_7_2 west dt1)
      (visible pos_7_3 east bt2)
      (visible pos_7_3 east bt3)
      (visible pos_7_3 east pt1)
      (visible pos_7_3 north pt1)
      (visible pos_7_3 south bt1)
      (visible pos_7_3 south dt1)
      (visible pos_7_3 west dt1)
      (visible pos_7_3 west pt1)
      (visible pos_8_1 north bt2)
      (visible pos_8_1 north bt3)
      (visible pos_8_1 north pt1)
      (visible pos_8_1 west bt1)
      (visible pos_8_1 west dt1)
      (visible pos_8_2 east bt2)
      (visible pos_8_2 east bt3)
      (visible pos_8_2 north bt2)
      (visible pos_8_2 north bt3)
      (visible pos_8_2 north pt1)
      (visible pos_8_2 west bt1)
      (visible pos_8_2 west dt1)
      (visible pos_8_3 east bt2)
      (visible pos_8_3 east bt3)
      (visible pos_8_3 east pt1)
      (visible pos_8_3 north pt1)
      (visible pos_8_3 south bt1)
      (visible pos_8_3 west bt1)
      (visible pos_8_3 west dt1)
      (visible pos_8_3 west pt1)
      (visible pos_9_1 north bt2)
      (visible pos_9_1 north bt3)
      (visible pos_9_1 north pt1)
      (visible pos_9_1 west bt1)
      (visible pos_9_1 west dt1)
      (visible pos_9_2 north bt2)
      (visible pos_9_2 north bt3)
      (visible pos_9_2 north pt1)
      (visible pos_9_2 west bt1)
      (visible pos_9_2 west dt1)
      (visible pos_9_2 west pt1)
      (visible pos_9_3 north bt2)
      (visible pos_9_3 north bt3)
      (visible pos_9_3 north pt1)
      (visible pos_9_3 south bt1)
      (visible pos_9_3 west bt1)
      (visible pos_9_3 west dt1)
      (visible pos_9_3 west pt1)
      (above b4_dist2 b4)
      (above b1_dist3 b1_dist2)
      (above b1 b1_dist1)
      (left-of bt1 b3_dist1)
      (left-of bt1 b3)
      (left-of bt1 b1_dist2)
      (left-of bt1 b1)
      (left-of b6_dist1 bt1)
      (left-of b3_dist1 b3)
      (left-of b3_dist1 b1_dist2)
      (left-of b3_dist1 b1)
      (left-of b6_dist1 b3_dist1)
      (left-of b3 b1_dist2)
      (left-of b3 b1)
      (left-of b6_dist1 b3)
      (left-of b4 b4_dist1)
      (left-of b4 b5)
      (left-of b4_dist2 b4_dist1)
      (left-of b4_dist2 b5)
      (left-of b4_dist1 b5)
      (left-of b1_dist2 b1)
      (left-of b1_dist2 b5_dist1)
      (left-of b1_dist2 b2_dist2)
      (left-of b1_dist3 b1_dist1)
      (left-of b1 b5_dist1)
      (left-of b1 b2_dist2)
      (left-of b5_dist1 b2_dist2)
      (left-of b5_dist1 b6_dist1)
      (left-of b5 b2)
      (left-of b5 b2_dist1)
      (left-of b5 b6_dist2)
      (left-of b2_dist2 b6_dist1)
      (left-of b2 b2_dist1)
      (left-of b2 b6_dist2)
      (left-of b4 b2)
      (left-of b4_dist2 b2)
      (left-of b4_dist1 b2)
      (left-of b2_dist1 b6_dist2)
      (current n-1)
      (next n-1 n-2)
      (next n-2 n-3)
      (next n-3 n-4)
      (next n-4 n-5)
      (next-referent e-1 e-2)
      (next-referent e-2 e-3)
      (next-referent e-3 e-4)
   )

   (:goal (and (forall (?a - category  ?u - syntaxnode  ) (not (mustadjoin ?a ?u))) (forall (?a - category  ?u - syntaxnode  ) (not (subst ?a ?u))) (forall (?u - syntaxnode  ?x - individual  ) (not (distractor ?u ?x))) (forall (?P - predicate  ?x1 - individual  ) (not (needtoexpress-1 ?P ?x1)))))
)
