/* Generated By:JavaCC: Do not edit this line. TermParserConstants.java */
package crisp.termparser;

public interface TermParserConstants {

  int EOF = 0;
  int ATOM = 5;
  int VARIABLE = 6;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<ATOM>",
    "<VARIABLE>",
    "\"(\"",
    "\",\"",
    "\")\"",
  };

}
